import "./globals.css";

export const metadata = {
  title: "Nicholas",
  description: "Generated by create next app",
  icons: {
    icon: "/N.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>{children}</body>
    </html>
  );
}
